config/routes.rb
Livescore::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  namespace :admin do
    match 'schedule', :to => 'tournaments#schedule', :as => 'schedule'
    match 'games', :to => 'tournaments#games', :as => 'games'
    
    resources :tournaments do
      member do
        get :schedule
        get :generate_schedule
        get :games
      end
    end
    resources :poules, :teams, :games
    root :to => 'admin#index'
  end
  
  resources :tournaments do
    member do
      get :ranking
    end
  end
  
  match 'schedule', :to => 'tournaments#show', :as => 'schedule'
  match 'ranking', :to => 'tournaments#ranking', :as => 'ranking'
  match 'finals', :to => 'tournaments#finals', :as => 'finals'
  
  root :to => 'dashboard#index'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  attr_accessible :name
  
  has_many :poules
  has_many :games, :through => :poules
end

app/controllers/admin/tournaments_controller.rb
class Admin::TournamentsController < Admin::AdminController

  def index
    @tournaments = Tournament.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tournaments }
    end
  end

  def show
    @tournament = current_tournament

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tournament }
    end
  end

  def new
    @tournament = Tournament.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tournament }
    end
  end

  def edit
    @tournament = Tournament.find(params[:id])
  end

  def create
    @tournament = Tournament.new(params[:tournament])

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to admin_tournament_path(@tournament), notice: 'Tournament was successfully created.' }
        format.json { render json: @tournament, status: :created, location: @tournament }
      else
        format.html { render action: "new" }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      if @tournament.update_attributes(params[:tournament])
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def generate_schedule
    tournament = Tournament.find(params[:id])
    
    tournament.poules.each do |poule|
      poule.games.delete_all
      poule.schedule.gamedays.each do |gameday|
        gameday.games.each do |match|
          Game.create!(:home_id => match.team_a, :away_id => match.team_b, :poule_id => poule.id)
        end
      end
    end
    
    redirect_to schedule_admin_tournament_path(@tournament), notice: 'Toernooischema gegenereerd.'
  end

  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
    end
  end
  
  def schedule
    @page = 'schedule'
    @tournament = current_tournament
  end
  
  def games
    @page = 'games'    
    @tournament = current_tournament
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  
  def show
    @tournament = current_tournament
  end
  
  def ranking
    @tournament = current_tournament
  end
  
  def finals
    @tournament = current_tournament
  end

end

app/helpers/admin/tournaments_helper.rb
module Admin::TournamentsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/admin/tournaments/_form.html.haml
= simple_form_for [:admin, @tournament] do |f|
  = f.input :name
  = f.input :subdomain
  = f.button :submit

app/views/admin/tournaments/_poules.html.haml
- @tournament.poules.each do |poule|
  %div.poule.dib
    %h3= poule.name
    = simple_form_for [:admin, Team.new ], :remote => true do |p|
      = p.input :name, :label => false, :input_html => { :placeholder => "Nieuw team in poule #{poule.name}"}
      = p.hidden_field :poule_id, :value => poule.id
    %ul
      - poule.teams.each do |team|
        %li=team.name

app/views/admin/tournaments/edit.html.haml
%h1 Editing tournament
= render 'form'
= link_to 'Show', @tournament
|
\#{link_to 'Back', tournaments_path}

app/views/admin/tournaments/games.html.haml
#games= render @tournament.poules

app/views/admin/tournaments/index.html.haml
.well
  %p
    %h1 Selecteer een toernooi
  - @tournaments.each do |tournament|
    =link_to admin_tournament_path(tournament), :class => 'btn' do
      %h3=tournament.name

%p
  = link_to 'Nieuw toernooi', new_admin_tournament_path, :class => "btn"

app/views/admin/tournaments/new.html.haml
%h1 New tournament
= render 'form'
= link_to 'Back', admin_tournaments_path

app/views/admin/tournaments/schedule.html.haml
%h1
  = @current_tournament.name
  = link_to "(her)Genereer schema", generate_schedule_admin_tournament_path(@current_tournament), :class => 'btn', :confirm => 'Alle bestaande wedstrijden voor dit toernooi worden verwijderd.'
%hr
= render @current_tournament.poules

app/views/admin/tournaments/show.html.haml
%p
  %h1=@tournament.name
.well
  #poules= render "poules"

= simple_form_for [:admin, Poule.new ], :remote => true do |p|
  = p.input :name, :label => false, :input_html => { :placeholder => "Nieuwe poule toevoegen..."}
  = p.hidden_field :tournament_id, :value => @tournament.id

app/views/admin/tournaments/update_poules.js.erb
$("#poules").html('<%=escape_javascript(render "admin/tournaments/poules")%>');