config/routes.rb
Livescore::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  namespace :admin do
    match 'schedule', :to => 'tournaments#schedule', :as => 'schedule'
    match 'games', :to => 'tournaments#games', :as => 'games'
    
    resources :tournaments do
      member do
        get :schedule
        get :generate_schedule
        get :games
      end
    end
    resources :poules, :teams, :games
    root :to => 'admin#index'
  end
  
  resources :tournaments do
    member do
      get :ranking
    end
  end
  
  match 'schedule', :to => 'tournaments#show', :as => 'schedule'
  match 'ranking', :to => 'tournaments#ranking', :as => 'ranking'
  match 'finals', :to => 'tournaments#finals', :as => 'finals'
  
  root :to => 'dashboard#index'

end

app/models/poule.rb
class Poule < ActiveRecord::Base
  attr_accessible :name, :tournament_id
  
  has_many :teams
  has_many :games
  belongs_to :tournament
  
  validates_associated :tournament
  validates_presence_of :name, :tournament_id
  validates_uniqueness_of :name, :scope => :tournament_id
  
  def schedule
    t = []
    teams.each do |team|
      t << team.id
    end
    
    poule = RRSchedule::Schedule.new(
      :teams => t,
      :rules => [
        RRSchedule::Rule.new(:wday => 6)
      ],
      :start_date => Date.parse("2012/05/10"),
      :shuffle => false
    )
    
    return poule.generate
  end
  
  def ranking
    teams = []
    self.teams.each do |team|
      team.points = team.calulate_points
      teams << team
    end
    teams.sort! { |a,b| b.points <=> a.points }
  end
end

app/controllers/admin/poules_controller.rb
class Admin::PoulesController < Admin::AdminController
  def create
    @poule = Poule.new(params[:poule])

    respond_to do |format|
      if @poule.save
        format.html { redirect_to admin_poule_path(@poule), notice: 'Poule was successfully created.' }
        format.json { render json: @poule, status: :created, location: @poule }
        format.js   { 
          @tournament = @poule.tournament
          render "admin/tournaments/update_poules"
        }
      else
        format.html { render action: "new" }
        format.json { render json: @poule.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/poules_helper.rb
module PoulesHelper
end

app/views/admin/poules/_form.html.haml
= simple_form_for [:admin, @poule] do |f|
  = f.input :name
  = f.association :tournament
  = f.button :submit

app/views/admin/poules/_poule.html.haml
.dib{:style => "min-width:280px;"}
  %table.table{:style => "100%;"}
    %thead
      %tr
        %th{:colspan => 4}=poule.name
      %tr
        %th Thuis
        %th 
        %th Uit
        %th Uitslag
    %tbody
      = render poule.games

app/views/admin/poules/edit.html.haml
%h1 Editing poule
= render 'form'
= link_to 'Show', @poule
|
\#{link_to 'Back', poules_path}

app/views/admin/poules/index.html.haml
%h1 Listing poules
%table
  %tr
    %th Name
    %th Tournament
    %th
    %th
    %th
  - @poules.each do |poule|
    %tr
      %td= poule.name
      %td= poule.tournament_id
      %td= link_to 'Show', poule
      %td= link_to 'Edit', edit_poule_path(poule)
      %td= link_to 'Destroy', poule, confirm: 'Are you sure?', method: :delete
%br/
= link_to 'New Poule', new_poule_path

app/views/admin/poules/new.html.haml
%h1 New poule
= render 'form'
= link_to 'Back', poules_path

app/views/admin/poules/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @poule.name
%p
  %b Tournament:
  = @poule.tournament_id
= link_to 'Edit', edit_poule_path(@poule)
|
\#{link_to 'Back', poules_path}