config/routes.rb
Livescore::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  namespace :admin do
    match 'schedule', :to => 'tournaments#schedule', :as => 'schedule'
    match 'games', :to => 'tournaments#games', :as => 'games'
    
    resources :tournaments do
      member do
        get :schedule
        get :generate_schedule
        get :games
      end
    end
    resources :poules, :teams, :games
    root :to => 'admin#index'
  end
  
  resources :tournaments do
    member do
      get :ranking
    end
  end
  
  match 'schedule', :to => 'tournaments#show', :as => 'schedule'
  match 'ranking', :to => 'tournaments#ranking', :as => 'ranking'
  match 'finals', :to => 'tournaments#finals', :as => 'finals'
  
  root :to => 'dashboard#index'

end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :poule_id
  attr_accessor :points
  
  belongs_to :poule
  has_many :home_games, :class_name => 'Game', :foreign_key => 'home_id'
  has_many :away_games, :class_name => 'Game', :foreign_key => 'away_id'
  
  def calulate_points
    p = 0
    self.games.each do |game|
      if game.winner == self.id
        p = p + 3
      elsif game.winner == 0
        p = p + 1
      end
    end
    return p
  end
  
  def games
     self.home_games + self.away_games
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < Admin::AdminController

  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
        format.js   { 
          @tournament = @team.poule.tournament
          render "admin/tournaments/update_poules"
        }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/admin/teams/_form.html.haml
= simple_form_for [:admin, @team] do |f|
  = f.input :name
  = f.association :poule
  = f.button :submit

app/views/admin/teams/edit.html.haml
%h1 Editing team
= render 'form'
= link_to 'Show', @team
|
\#{link_to 'Back', teams_path}

app/views/admin/teams/index.html.haml
%h1 Listing teams
%table
  %tr
    %th Name
    %th Poule
    %th
    %th
    %th
  - @teams.each do |team|
    %tr
      %td= team.name
      %td= team.poule_id
      %td= link_to 'Show', team
      %td= link_to 'Edit', edit_team_path(team)
      %td= link_to 'Destroy', team, confirm: 'Are you sure?', method: :delete
%br/
= link_to 'New Team', new_team_path

app/views/admin/teams/new.html.haml
%h1 New team
= render 'form'
= link_to 'Back', teams_path

app/views/admin/teams/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @team.name
%p
  %b Poule:
  = @team.poule_id
= link_to 'Edit', edit_team_path(@team)
|
\#{link_to 'Back', teams_path}