config/routes.rb
Livescore::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  namespace :admin do
    match 'schedule', :to => 'tournaments#schedule', :as => 'schedule'
    match 'games', :to => 'tournaments#games', :as => 'games'
    
    resources :tournaments do
      member do
        get :schedule
        get :generate_schedule
        get :games
      end
    end
    resources :poules, :teams, :games
    root :to => 'admin#index'
  end
  
  resources :tournaments do
    member do
      get :ranking
    end
  end
  
  match 'schedule', :to => 'tournaments#show', :as => 'schedule'
  match 'ranking', :to => 'tournaments#ranking', :as => 'ranking'
  match 'finals', :to => 'tournaments#finals', :as => 'finals'
  
  root :to => 'dashboard#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :away_id, :away_score, :home_id, :home_score, :poule_id
  
  belongs_to :home_team, :class_name => 'Team', :foreign_key => 'home_id'
  belongs_to :away_team, :class_name => 'Team', :foreign_key => 'away_id'
  belongs_to :poule
  
  validates_presence_of :home_id, :away_id, :poule_id
  validates_uniqueness_of :home_id, :scope => [ :poule_id, :away_id ]
  
  scope :recent, :limit => 10, :order => 'updated_at DESC'
  
  def winner
    if !home_score.nil? and !away_score.nil?      
      if home_score.to_i > away_score.to_i
        return home_id
      elsif home_score.to_i < away_score.to_i
        return away_id
      else
        return 0
      end
    else
      return nil
    end
  end

end

app/models/poule.rb
class Poule < ActiveRecord::Base
  attr_accessible :name, :tournament_id
  
  has_many :teams
  has_many :games
  belongs_to :tournament
  
  validates_associated :tournament
  validates_presence_of :name, :tournament_id
  validates_uniqueness_of :name, :scope => :tournament_id
  
  def schedule
    t = []
    teams.each do |team|
      t << team.id
    end
    
    poule = RRSchedule::Schedule.new(
      :teams => t,
      :rules => [
        RRSchedule::Rule.new(:wday => 6)
      ],
      :start_date => Date.parse("2012/05/10"),
      :shuffle => false
    )
    
    return poule.generate
  end
  
  def ranking
    teams = []
    self.teams.each do |team|
      team.points = team.calulate_points
      teams << team
    end
    teams.sort! { |a,b| b.points <=> a.points }
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :poule_id
  attr_accessor :points
  
  belongs_to :poule
  has_many :home_games, :class_name => 'Game', :foreign_key => 'home_id'
  has_many :away_games, :class_name => 'Game', :foreign_key => 'away_id'
  
  def calulate_points
    p = 0
    self.games.each do |game|
      if game.winner == self.id
        p = p + 3
      elsif game.winner == 0
        p = p + 1
      end
    end
    return p
  end
  
  def games
     self.home_games + self.away_games
  end
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  attr_accessible :name
  
  has_many :poules
  has_many :games, :through => :poules
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_user!
  layout "admin"
  
  def index    
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < Admin::AdminController
  def index
  end

  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.js   { 
          render "admin/games/updated"
        }
      else
        format.html { render action: "edit" }
      end
    end
  end
end

app/controllers/admin/poules_controller.rb
class Admin::PoulesController < Admin::AdminController
  def create
    @poule = Poule.new(params[:poule])

    respond_to do |format|
      if @poule.save
        format.html { redirect_to admin_poule_path(@poule), notice: 'Poule was successfully created.' }
        format.json { render json: @poule, status: :created, location: @poule }
        format.js   { 
          @tournament = @poule.tournament
          render "admin/tournaments/update_poules"
        }
      else
        format.html { render action: "new" }
        format.json { render json: @poule.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < Admin::AdminController

  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
        format.js   { 
          @tournament = @team.poule.tournament
          render "admin/tournaments/update_poules"
        }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :current_tournament
  
  def current_tournament
    @current_tournament = Tournament.find_by_subdomain(request.subdomain)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def index
    @games = current_tournament.games.recent
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  
  def show
    @tournament = current_tournament
  end
  
  def ranking
    @tournament = current_tournament
  end
  
  def finals
    @tournament = current_tournament
  end

end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/tournaments_helper.rb
module Admin::TournamentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/poules_helper.rb
module PoulesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/admin/admin/index.html.haml
Admin index

app/views/layouts/_flashmessages.html.haml
- flash.each do |name, msg|
  = content_tag :div, msg, :class => "alert alert-#{name}"

app/views/layouts/admin.html.haml
!!! XML
!!!
%html
  %head
    %title Livescore
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    = stylesheet_link_tag "admin"
    = javascript_include_tag "admin"
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          =link_to "#{@current_tournament.name}", root_url, :class => 'brand'
          .nav-collapse
            %ul.nav
              %li{:class => ( @page == 'games' ? 'active' : '')}=link_to "Wedstrijden", admin_games_path
              %li{:class => ( @page == 'schedule' ? 'active' : '')}=link_to "Toernooi manager", admin_schedule_path
    .container
      = render "layouts/flashmessages"
      =yield

app/views/layouts/application.html.haml
!!! XML
!!!
%html
  %head
    %title Livescore
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          =link_to @current_tournament.name, root_url, :class => 'brand'
          .nav-collapse
            %ul.nav
              %li=link_to "Uitslagen & Programma", schedule_path
              %li=link_to "Stand", ranking_path
    .container
      = render "layouts/flashmessages"
      =yield

app/views/layouts/login.html.haml
!!! XML
!!!
%html
  %head
    %title Livescore
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          =link_to "LiveScore", root_url, :class => 'brand'
    .container
      =yield